id: I661AAAA6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:34:50+00:00'
last_modified: '2022-06-10T05:51:42.970054+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19829
  title: འབོ་གངས་དཀར་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    496C:
      image_group_id: I1GS105450
      title: Volume 1 of 'bo gangs dkar rnam thar
      total_pages: 104
      order: 1
      base_file: 496C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
